--- #YAML:1.0
name:                Log-Log4perl-Appender-ScreenColoredLevels-UsingMyColors
version:             0.10_01
abstract:            Colorize messages according to level amd my colors
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Log::Log4perl::Level:          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
